---
language: python
services: docker

env:
  matrix:
    # Test defaults.
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604

    # Test other role features.
    - MOLECULE_DISTRO: centos7
      MOLECULE_PLAYBOOK: playbook-java11.yml
    - MOLECULE_DISTRO: ubuntu1804
      MOLECULE_PLAYBOOK: playbook-java11.yml

install:
  # Install test dependencies.
  - pip install molecule docker

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
