---
name: Molecule Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        molecule_distro: ['centos7', 'centos8', 'ubuntu1804', 'ubuntu2004']
        java_version: ['8', '11']
        include:
          - molecule_distro: centos7
            java_version: latest
          - molecule_distro: centos8
            java_version: latest
          - molecule_distro: ubuntu2004
            java_version: 13
          - molecule_distro: ubuntu2004
            java_version: 14

    env:
      ANSIBLE_CALLBACK_WHITELIST: profile_tasks

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint flake8 molecule molecule-docker docker yamllint
          ansible --version
          ansible-lint --version
          molecule --version
      - name: Test with molecule
        run: |
          molecule test --all
        env:
          MOLECULE_DISTRO: ${{ matrix.molecule_distro }}
          JAVA_VERSION: ${{ matrix.java_version }}
